### ISSUE TITLE
Facing issues working with castro

### ISSUE THREAD

**Issue by Jay011191** [hugs/castro#7]
Here's my code---
import castro
video = castro.Castro()
video.start()

The error is -

> > > Socket error: [Errno 111] Connection refused
> > > Process Process-1:
> > > Traceback (most recent call last):
> > >   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> > >     self.run()
> > >   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
> > >     self._target(_self._args, *_self._kwargs)
> > >   File "/usr/local/lib/python2.7/dist-packages/castro-1.0.6-py2.6.egg/castro/lib/pyvnc2swf/vnc2swf.py", line 611, in main
> > >     merge=merge, debug=debug, reconnect=reconnect)
> > >   File "/usr/local/lib/python2.7/dist-packages/castro-1.0.6-py2.6.egg/castro/lib/pyvnc2swf/vnc2swf.py", line 429, in vnc2swf
> > >     client.loop()
> > >   File "/usr/local/lib/python2.7/dist-packages/castro-1.0.6-py2.6.egg/castro/lib/pyvnc2swf/rfb.py", line 489, in loop
> > >     if not self.loop1(): break
> > >   File "/usr/local/lib/python2.7/dist-packages/castro-1.0.6-py2.6.egg/castro/lib/pyvnc2swf/rfb.py", line 276, in loop1
> > >     self.request_update()
> > >   File "/usr/local/lib/python2.7/dist-packages/castro-1.0.6-py2.6.egg/castro/lib/pyvnc2swf/rfb.py", line 551, in request_update
> > >     self.send('\x03\x01' + pack('>HHHH', *self.clipping))
> > > AttributeError: RFBNetworkClient instance has no attribute 'clipping'

**Comment by legna84426644** [comment]
This is the issue of connecting to vnc server. You need to check your vnc connection first
