### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by VanDavv** [hugs/castro#9]
Just instaled castro in my project, where I use python 3.6 and got following error

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/usr/local/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
>     __import__(name)
>   File "/app/src/test_auth.py", line 1, in <module>
>     from .base import SeleniumTestCase
>   File "/app/src/base.py", line 9, in <module>
>     from castro import Castro
>   File "/usr/local/lib/python3.6/site-packages/castro/__init__.py", line 110
>     print "Running ffmpeg: encoding and creating keyframes"
>                                                           ^
> SyntaxError: Missing parentheses in call to 'print'

This is obviously python2 syntax, it would be nice to have a package that uses python 3

**Comment by saily** [comment]
@VanDavv @hugs i'd happy to help here.

**Comment by stivens13** [comment]
> SyntaxError: Missing parentheses in call to 'print'

This is exactly what happened to me. I edited the file where the problem occurred, but after doing so the chain continues

`Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    from castro import Castro
  File "/usr/local/lib/python3.6/site-packages/castro/__init__.py", line 10, in <module>
    import lib.messageboard as mb
ModuleNotFoundError: No module named 'lib'
`

Obviously, some refactoring required for python 3. Why is this package available for install if it uses python 2 syntax? Why using python 2 syntax if python 3 syntax is reverse compatible?

**Comment by antedesk** [comment]
I had the same issues reported above. 
It'd be awesome to have the porting of this library to python3.

**Comment by VanDavv** [comment]
@saily @Stivens73 @antedesk let's create MR and one by one fix any issue related to python3 migration, how about that?

**Comment by VanDavv** [comment]
This fork should have python3 supported - https://github.com/emazzotta/castro

**Comment by saily** [comment]
@hugs do you still maintain the project? 
if we put effort on this, do you accept merge requests, or should we fork it as @VanDavv already pointed out.

**Comment by zmskco** [comment]
It is recommended to use [xvfbwrapper](https://pypi.org/project/xvfbwrapper/).

**Comment by saily** [comment]
Sorry but this does not anser the question. Was there an official message from castro maintainers? I would prefer and contribute porting castro to py3 as xvfbwrapper does not provide features as screen recording.

**Comment by VanDavv** [comment]
[This diff](https://github.com/critiqueit/castro/commit/f8643c7e0d299a2253e0e37a7fa7d973b26d995a) has everything in place to support python3. I suggest we should create `casto3` project where all the codebase would be copied and this commit from @critiqueit would be cherry-picked. 

This way we can resurrect this abandoned library, as I assume from the inactivity of it's contributors it is

**Comment by philall** [comment]
> [This diff](https://github.com/critiqueit/castro/commit/f8643c7e0d299a2253e0e37a7fa7d973b26d995a) has everything in place to support python3. I suggest we should create `casto3` project where all the codebase would be copied and this commit from @critiqueit would be cherry-picked.
> 
> This way we can resurrect this abandoned library, as I assume from the inactivity of it's contributors it is

Has anything been done in this direction?

**Comment by saily** [comment]
/ping @hugs could you please comment on this before @philall is going to (hopefully) fork (and not copying) it.

**Comment by 2Niu** [comment]
Bad news, It does not support Python3  yet.
